### ISSUE TITLE
Improve task to sign GM files

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-process#29]
This is a response from Michael to a request to sign GM files:

On Mon, Jul 15, 2019 at 10:08:49AM +0200, Adrian Schröter wrote:
> On Freitag, 12. Juli 2019, 20:38:13 CEST Lubos Kocman wrote:
> > Hello team,
> > 
> > this is part of a task https://progress.opensuse.org/issues/52034
> > 
> > I'd like to ask you to copy signkey for staging project to 
> > openSUSE:Leap:15.2 from a previous release.
> 
> done

You also have to copy the ssl cert. Now done.

Cheers,
  Michael.

**Comment by lnussel** [comment]
signing the GM has nothing to do with the initial project setup!?

**Comment by lkocman** [comment]
Ah yes, somehow the email from July 2019 popped up next to my sign request and I copied a note from that.

Thanks for noticing.
