### ISSUE TITLE
update and merge counter.o.o instructions

### ISSUE THREAD

**Issue by cboltz** [openSUSE/openSUSE-release-process#68]
RC.md has
```
make counter.o.o/link point to new portal

https://counter.opensuse.org/link/ should point to https://en.opensuse.org/Portal:15.1?pk_campaign=counter
```

GA.md has
```
Create release counter

Start kicking the artwork team: we need the release counter updated!

https://github.com/openSUSE/countdown.o.o
```

While these are not completely wrong, I see two issues with them:
* RC and GA are too late IMHO. Both the counter and the link should be updated earlier, probably during beta phase (and, most important, at the same time)
* the link target is managed in salt, so please extend the instructions to something like `ask the heroes to update the link in salt (pillar/role/countdown.sls)`

It's probably a good idea to merge everything into one counter.o.o task.

**Comment by lkocman** [comment]
Fixed
